env: "local"
storage_path: "./storage.db"
http_server: 
  address: localhost:8082
  timeout: 4s
  idle_timeout: 60s

database:
  host: database  # Имя сервиса из docker-compose
  port: 5432
  user: postgres
  password: postgres
  db_name: postgres
  ssl_mode: disable
