version: "3.9"
services:
  app:
    build: .
    ports:
      - "8082:8082"
    environment:
      CONFIG_PATH: /config/local.yaml
    volumes:
      - ./config.yaml:/config/local.yaml
    depends_on:
      - db

  db:
    image: postgres:15
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: app_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
