version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8082:8082" # Пробрасываем порт для приложения
    environment:
      - CONFIG_PATH=/app/config/local.yaml # путь к конфигурации
      - DB_HOST=database # Имя сервиса для подключения
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=postgres
    depends_on:
      database:
        condition: service_healthy # Условие запуска, если healthcheck настроен

  database:
    image: postgres:15
    container_name: postgres_container
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432" # Пробрасываем порт PostgreSQL
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: # Для хранения данных PostgreSQL вне контейнера
